import { GENDER, MEMBERSHIP, UserEntity } from '@/@model/user.entity';

export const UserSeed: Partial<UserEntity>[] = [
    {
        name: 'Gunawan Prasetya',
        email: 'gunawan.pras776@gmail.com',
        username: 'gunawan.pras',
        password: 'gunawan123@!',
        birth_date: new Date('1992-08-23'),
        gender: GENDER.Male,
        address: 'Jl. Cililitan no24, Cililitan, Jakarta Timur, DKI Jakarta',
        photo: 'https://e1.pxfuel.com/desktop-wallpaper/397/677/desktop-wallpaper-35-foto-cewek-cantik-indonesia-idaman-para-cowok-cewe-cantik.jpg',
        profile_desc: '',
        phone_number: '082135230995',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Dewi Santoso',
        email: 'dewi.santoso999@gmail.com',
        username: 'dewi.sant',
        password: 'dewi2024@!',
        birth_date: new Date('1991-02-12'),
        gender: GENDER.Female,
        address: 'Jl. Mangga Dua no8, Mangga Dua, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxa6eyftY7m9AqP6FgA3kgd0_sUJ8kZy_nkbQO5T=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081238764321',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Ahmad Ramadhan',
        email: 'ahmad.ramadhan53@gmail.com',
        username: 'ahmad.ram',
        password: 'ramadhan2024@!',
        birth_date: new Date('2001-01-20'),
        gender: GENDER.Male,
        address: 'Jl. Buncit Raya no20, Mampang, Jakarta Selatan, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxZbsofjQdtIADFH8SAxe4KJq6A4kN3cgj9g_Jw=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085673456789',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Siti Nurhaliza',
        email: 'siti.nurhaliza77@gmail.com',
        username: 'siti.nur',
        password: 'nurhaliza2024@!',
        birth_date: new Date('1999-03-18'),
        gender: GENDER.Female,
        address: 'Jl. Tebet Raya no13, Tebet, Jakarta Selatan, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxZGZKveZJxS-UbkB88r7L13ZROGNGqqvHjtYDsR=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082137654321',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Budi Setiawan',
        email: 'budi.setiawan82@gmail.com',
        username: 'budi.set',
        password: 'budi2024@!',
        birth_date: new Date('1989-12-12'),
        gender: GENDER.Male,
        address: 'Jl. Sudirman no45, Kebayoran Baru, Jakarta Selatan, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxbFJ8OjT-eK7J5DPLovm8fp-evQQOpzo-ly1Vo=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085612345678',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Agus Wijaya',
        email: 'agus.wijaya22@gmail.com',
        username: 'agus.wij',
        password: 'agus2024@!',
        birth_date: new Date('1980-10-29'),
        gender: GENDER.Male,
        address: 'Jl. Kebon Jeruk no2, Kebon Jeruk, Jakarta Barat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxaDgEgzfs5WFXP-fj48Thz1U3aXJ9tRzYJ9KEcZ=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081245678912',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Rina Kusuma',
        email: 'rina.kusuma88@gmail.com',
        username: 'rina.kus',
        password: 'rina2024@!',
        birth_date: new Date('1995-03-21'),
        gender: GENDER.Female,
        address: 'Jl. Tanah Abang no19, Tanah Abang, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxZ2-N-IB5KSUxwsHyoOXPUddJ5-bfwXkqSYZME=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082167894512',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Doni Kurniawan',
        email: 'doni.kurniawan34@gmail.com',
        username: 'doni.kur',
        password: 'doni2024@!',
        birth_date: new Date('1995-07-23'),
        gender: GENDER.Male,
        address: 'Jl. Senen Raya no8, Senen, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxZ7s44El2zbxKwY0o3ifG6ztD0wlirfP78DUNef=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085678932145',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Yuni Astuti',
        email: 'yuni.astuti77@gmail.com',
        username: 'yuni.ast',
        password: 'yuni2024@!',
        birth_date: new Date('2000-11-23'),
        gender: GENDER.Female,
        address: 'Jl. Pulo Gadung no12, Pulo Gadung, Jakarta Timur, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxYbB54ewDngtI-Z4hN2wQQh2J1dt7O7RxGsLdpV=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082156789431',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Joko Susilo',
        email: 'joko.susilo99@gmail.com',
        username: 'joko.sus',
        password: 'joko2024@!',
        birth_date: new Date('2003-05-03'),
        gender: GENDER.Male,
        address: 'Jl. Kalimalang no5, Kalimalang, Jakarta Timur, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxavvFbZ6QqTKFHbD22WJv5sJqPzT0GZApA0sMQ=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081234567891',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Tuti Wulandari',
        email: 'tuti.wulandari66@gmail.com',
        username: 'tuti.wul',
        password: 'tuti2024@!',
        birth_date: new Date('1997-02-22'),
        gender: GENDER.Female,
        address: 'Jl. Cikini Raya no3, Cikini, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxYXNzpThqAa7zV0H_iN9-W0vY_E4SVSpbClS4T6=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082145678932',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Andi Pratama',
        email: 'andi.pratama55@gmail.com',
        username: 'andi.prat',
        password: 'andi2024@!',
        birth_date: new Date('1999-08-27'),
        gender: GENDER.Male,
        address: 'Jl. Salemba Raya no1, Salemba, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxYlRWv0zOgGFL9tmD9WaVtIHzCFPT9DN_WT5R4=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085678923145',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Lina Hartati',
        email: 'lina.hartati89@gmail.com',
        username: 'lina.hart',
        password: 'lina2024@!',
        birth_date: new Date('1995-07-12'),
        gender: GENDER.Female,
        address: 'Jl. Sudirman no55, Kebayoran Baru, Jakarta Selatan, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxa7RsiJXyHzFTVCjAhR2u8dGPgyur0nxTZ5kkKk=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082137894516',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Rizki Pratama',
        email: 'rizki.pratama33@gmail.com',
        username: 'rizki.prat',
        password: 'rizki2024@!',
        birth_date: new Date('1994-03-19'),
        gender: GENDER.Male,
        address: 'Jl. Thamrin no15, Thamrin, Jakarta Pusat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxYt09F-GjkQ3HNYJDgJj7Eu9ZbXz7Fh4KTzD96j=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085612349876',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Ratna Sari',
        email: 'ratna.sari44@gmail.com',
        username: 'ratna.sar',
        password: 'ratna2024@!',
        birth_date: new Date('1993-04-14'),
        gender: GENDER.Female,
        address: 'Jl. Matraman no23, Matraman, Jakarta Timur, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxZLpbfjW57gMh0ihHRXN6bXrsErh2KD_Hg5EBY=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082134567892',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Hendra Saputra',
        email: 'hendra.saputra99@gmail.com',
        username: 'hendra.sap',
        password: 'hendra2024@!',
        birth_date: new Date('1994-02-25'),
        gender: GENDER.Male,
        address: 'Jl. Merdeka no6, Merdeka, Jakarta Barat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxZx_pMSKbxPzG8-xK02T5oD-RUJwOeT9j5k5yE=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081234678923',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Mira Astari',
        email: 'mira.astari77@gmail.com',
        username: 'mira.ast',
        password: 'mira2024@!',
        birth_date: new Date('2001-05-16'),
        gender: GENDER.Female,
        address: 'Jl. Kelapa Gading no18, Kelapa Gading, Jakarta Utara, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxaPXrNYJeT_g8qIvNVDJlN2fwV43axZT3C5Pp4=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082176543218',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Fajar Rahman',
        email: 'fajar.rahman33@gmail.com',
        username: 'fajar.rah',
        password: 'fajar2024@!',
        birth_date: new Date('2000-06-13'),
        gender: GENDER.Male,
        address: 'Jl. Pluit no11, Pluit, Jakarta Utara, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxa-3d1VbZg3tAUbJdS6o3a7CQyDRvQYlFj1EfFQ=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '085673412389',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Intan Permata',
        email: 'intan.permata88@gmail.com',
        username: 'intan.per',
        password: 'intan2024@!',
        birth_date: new Date('1996-05-25'),
        gender: GENDER.Female,
        address: 'Jl. Ancol Barat no2, Ancol, Jakarta Utara, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxbv89GVQFMEY7akYfGlvMrRZQpThmObpq1AX1FU=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082143567892',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Teguh Purnomo',
        email: 'teguh.purnomo66@gmail.com',
        username: 'teguh.pur',
        password: 'teguh2024@!',
        birth_date: new Date('1990-04-24'),
        gender: GENDER.Male,
        address: 'Jl. Slipi Raya no9, Slipi, Jakarta Barat, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxZ5WBSW4IK60TBhONhME_wOD3c_zGhlKzp7cL8o=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081234598716',
        membership: MEMBERSHIP.Basic,
    },
    {
        name: 'Wulan Sari',
        email: 'wulan.sari77@gmail.com',
        username: 'wulan.sar',
        password: 'wulan2024@!',
        birth_date: new Date('1998-12-05'),
        gender: GENDER.Female,
        address: 'Jl. Blok M no10, Blok M, Jakarta Selatan, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a/AGNmyxYkTRJHNhS1bzxINzKCy2XPLiHv0JX9E7SpbyMP=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '082145678932',
        membership: MEMBERSHIP.Premium,
    },
    {
        name: 'Eko Prasetyo',
        email: 'eko.prasetyo99@gmail.com',
        username: 'eko.pras',
        password: 'eko2024@!',
        birth_date: new Date('1999-09-14'),
        gender: GENDER.Male,
        address: 'Jl. Rawamangun no14, Rawamangun, Jakarta Timur, DKI Jakarta',
        photo: 'https://lh3.googleusercontent.com/a-/AGNmyxboqCkGHc-20uYPqX2N7VUnVmk2egQz4SbxjsQ=s128-c-rp-mo',
        profile_desc: '',
        phone_number: '081234567890',
        membership: MEMBERSHIP.Basic,
    }
];
